import {ChronicleTemplate} from './types';

export const defaultChronicleTemplate: ChronicleTemplate = {
  canvas: {width: 1080, height: 1920, fps: 24},
  palette: {
    bg: '#070B10',
    bg_glow: '#165A82',
    accent: '#3DDCFF',
    accent_dim: '#1A6A8A',
    text: '#F4F7FA',
    text_muted: '#8B96A8',
    card: '#FFFFFF',
    frame: '#1A6A8A',
  },
  chrome: {
    brand: '小牛聊AI',
    mark_glyph: '牛',
    brand_sub: '粉碎AI信息差 / 消除AI焦虑',
    footer_left: 'AI 快讯',
  },
  typography: {
    title_font_size: 64,
    subtitle_font_size: 47,
    brand_font_size: 43,
    brand_sub_font_size: 28,
    footer_font_size: 40,
    summary_y_percent: 73.2,
    footer_y_percent: 87.0,
    summary_font_size: 38,
    summary_width_percent: 84,
    summary_align: 'left',
    top_pad_percent: 5,
    title_highlight_color: '#FFEC30',
    main_line1_color: '#F4F7FA',
    subtitle2_color: '#3DDCFF',
  },
  layout: {
    card_top_percent: 35,
    card_bottom_percent: 71,
    card_left_percent: 8,
    card_right_percent: 92,
    card_inset_px: 16,
  },
  video: {
    summary_animation: {
      mode: 'typewriter',
      scope: 'once',
      chars_per_second: 14,
      start_delay_sec: 0.35,
      show_cursor: true,
      cursor_blink_hz: 2,
      cursor_hide_after_done_sec: 0.5,
    },
    card_motion: {
      enabled: true,
      random: true,
      end_scale: 1.22,
      pan_percent: 70,
      effects: [
        'zoom_in',
        'zoom_out',
        'pan_left',
        'pan_right',
        'pan_up',
        'pan_down',
        'zoom_in_left',
        'zoom_in_right',
        'zoom_in_up',
        'zoom_in_down',
      ],
    },
  },
};
